# Generated by Django 5.1.2 on 2024-11-04 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("paper_graph", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="paper",
            name="paper_url",
            field=models.URLField(default=""),
        ),
    ]
